import { faker } from "@faker-js/faker";
const vinGenerator = require("vin-generator");
var moment = require("moment");
export const testCases = {
  case1: {
    case: "Creating a Cash Sale by adding DCC/GAP",
    caseNo: "case1",
    first_name: faker.name.firstName().replace("'", ""),
    last_name: faker.name.lastName().replace("'", ""),
    phone: faker.phone.number("3##-###-####"),
    street: faker.address.street(),
    zipcode: "75901",
    full_name: "xyz",
    bhphOrOutsideFinance: false,
    sale_date: "12/12/2022",
    vehicle_price: "10,000.00",
    totalSalePrice: "11,098.01",
    finalizeSale: true,
    saleType: "cash",
    typeOfSale: 2,
    apr: "24.82",
    financeCharge: "3,195.98",
    amountFinanced: "7,890.51",
    totalOfPayments: "11,086.49",
    noOfPayments: "35",
    installmentAmount: "312.97",
    dealerTradeInOffer: "7,000.00",
    payOffLoanBalance: "2,000.00",
    cashPaidToBuyer: "2,000.00",
    actualCashValue: "8,000.00",
    tradeInContains: false,
    tradeInVehicleYear: "2000",
    tradeInVehicleVIN: "5TFUM5F12AX012971",
    tradeInStock: "",
    tradeVehicleMileage: "",
    tradeInVehiclelicensePlate: " N/A ",
    tradeInVehicleMake: " ",
    tradeInVehicleModel: " ",
    differedDate: moment().add(10, "days").format("MM/DD/YYYY"),
    differedDownPaymentAmount: "20",
    dccGapType: "DCC",
    vendorName: "qwerty",
    dccGapDealerPrice: "200",
    dccGapCostPrice: "230",
    salesPerson: "clearent",
    salesPerson2: "clearent",
    deffDownpaymentContains: false,
    downPayment: "11,098.01",
    containsDownPayment: false,
    otherThanBHPH: true,
    commissionCalculation: "0",
    commissionRate: "2.00%",
    commission: "$ 150.00",
    profitOnVehicle: "9,687.00",
    otherCalculation: "9,769.00",
    otherCommissionRate: "2.00",
    otherCommission: "$ 195.38",
    BHPH: true,
    documentaryFee: "52.00",
    salesTax: "625.00",
    governmentFee: "162.01",
    serviceContract: "0",
    dccGap: "230.00",
    inventoryTax: "29.00",
    totalSalesPrice: "11,098.01",
    total: "11,098.01",
    lienHolder: "qwerty",
    taxInclude: "no",
  },
  case2: {
    case: "Creating a Cash Sale by adding Service Contract",
    caseNo: "case2",
    first_name: faker.name.firstName().replace("'", ""),
    last_name: faker.name.lastName().replace("'", ""),
    phone: faker.phone.number("3##-###-####"),
    street: faker.address.street(),
    zipcode: "75901",
    full_name: "xyz",
    bhphOrOutsideFinance: false,
    sale_date: "12/12/2022",
    vehicle_price: "10,000.00",
    totalSalePrice: "11,118.01",
    finalizeSale: true,
    saleType: "cash",
    typeOfSale: 2,
    apr: "24.82",
    financeCharge: "3,195.98",
    amountFinanced: "7,890.51",
    totalOfPayments: "11,086.49",
    noOfPayments: "35",
    installmentAmount: "312.97",
    dealerTradeInOffer: "7,000.00",
    payOffLoanBalance: "2,000.00",
    cashPaidToBuyer: "2,000.00",
    actualCashValue: "8,000.00",
    tradeInContains: false,
    tradeInVehicleYear: "2000",
    tradeInVehicleVIN: "5TFUM5F12AX012971",
    tradeInStock: "",
    tradeVehicleMileage: "",
    tradeInVehiclelicensePlate: " N/A ",
    tradeInVehicleMake: " ",
    tradeInVehicleModel: " ",
    differedDate: moment().add(10, "days").format("MM/DD/YYYY"),
    differedDownPaymentAmount: "20",
    dccGapType: "DCC",
    vendorName: "qwerty",
    dccGapDealerPrice: "200",
    dccGapCostPrice: "230",
    salesPerson: "clearent",
    salesPerson2: "clearent",
    deffDownpaymentContains: false,
    downPayment: "11,118.01",
    containsDownPayment: false,
    otherThanBHPH: true,
    commissionCalculation: "0",
    commissionRate: "2.00%",
    commission: "$ 150.00",
    profitOnVehicle: "9,687.00",
    otherCalculation: "9,769.00",
    otherCommissionRate: "2.00",
    otherCommission: "$ 195.38",
    BHPH: true,
    documentaryFee: "52.00",
    salesTax: "625.00",
    governmentFee: "162.01",
    serviceContract: "250.00",
    dccGap: "0",
    inventoryTax: "29.00",
    totalSalesPrice: "11,118.01",
    total: "11,118.01",
    lienHolder: "qwerty",
    taxInclude: "no",
  },
  case3: {
    case: "Creating a Cash Sale by adding TradeIn",
    caseNo: "case3",
    first_name: faker.name.firstName().replace("'", ""),
    last_name: faker.name.lastName().replace("'", ""),
    phone: faker.phone.number("3##-###-####"),
    street: faker.address.street(),
    zipcode: "75901",
    full_name: "xyz",
    bhphOrOutsideFinance: false,
    sale_date: "12/12/2022",
    vehicle_price: "10,000.00",
    totalSalePrice: "7,430.51",
    finalizeSale: true,
    saleType: "cash",
    typeOfSale: 2,
    apr: "24.82",
    financeCharge: "3,195.98",
    amountFinanced: "7,890.51",
    totalOfPayments: "11,086.49",
    noOfPayments: "35",
    installmentAmount: "312.97",
    dealerTradeInOffer: "7,000.00",
    payOffLoanBalance: "2,000.00",
    cashPaidToBuyer: "2,000.00",
    actualCashValue: "8,000.00",
    tradeInContains: true,
    tradeInVehicleYear: "2000",
    tradeInVehicleVIN: "5TFUM5F12AX012971",
    tradeInStock: "",
    tradeVehicleMileage: "",
    tradeInVehiclelicensePlate: " N/A ",
    tradeInVehicleMake: " ",
    tradeInVehicleModel: " ",
    differedDate: moment().add(10, "days").format("MM/DD/YYYY"),
    differedDownPaymentAmount: "20",
    dccGapType: "DCC",
    vendorName: "qwerty",
    dccGapDealerPrice: "200",
    dccGapCostPrice: "230",
    salesPerson: "clearent",
    salesPerson2: "clearent",
    deffDownpaymentContains: false,
    downPayment: "7,430.51",
    containsDownPayment: false,
    otherThanBHPH: true,
    commissionCalculation: "0",
    commissionRate: "2.00%",
    commission: "$ 150.00",
    profitOnVehicle: "9,687.00",
    otherCalculation: "9,769.00",
    otherCommissionRate: "2.00",
    otherCommission: "$ 195.38",
    BHPH: true,
    documentaryFee: "52.00",
    salesTax: "187.50",
    governmentFee: "162.01",
    serviceContract: "0",
    dccGap: "0",
    inventoryTax: "29.00",
    totalSalesPrice: "7,430.51",
    total: "7,430.51",
    lienHolder: "qwerty",
    taxInclude: "no",
  },
  case4: {
    case: "Creating a Cash Sale by adding TradeIn and Service Contract",
    caseNo: "case4",
    first_name: faker.name.firstName().replace("'", ""),
    last_name: faker.name.lastName().replace("'", ""),
    phone: faker.phone.number("3##-###-####"),
    street: faker.address.street(),
    zipcode: "75901",
    full_name: "xyz",
    bhphOrOutsideFinance: false,
    sale_date: "12/12/2022",
    vehicle_price: "10,000.00",
    totalSalePrice: "7,680.51",
    finalizeSale: true,
    saleType: "cash",
    typeOfSale: 2,
    apr: "24.82",
    financeCharge: "3,195.98",
    amountFinanced: "7,890.51",
    totalOfPayments: "11,086.49",
    noOfPayments: "35",
    installmentAmount: "312.97",
    dealerTradeInOffer: "7,000.00",
    payOffLoanBalance: "2,000.00",
    cashPaidToBuyer: "2,000.00",
    actualCashValue: "8,000.00",
    tradeInContains: true,
    tradeInVehicleYear: "2000",
    tradeInVehicleVIN: "5TFUM5F12AX012971",
    tradeInStock: "",
    tradeVehicleMileage: "",
    tradeInVehiclelicensePlate: " N/A ",
    tradeInVehicleMake: " ",
    tradeInVehicleModel: " ",
    differedDate: moment().add(10, "days").format("MM/DD/YYYY"),
    differedDownPaymentAmount: "20",
    dccGapType: "DCC",
    vendorName: "qwerty",
    dccGapDealerPrice: "200",
    dccGapCostPrice: "230",
    salesPerson: "clearent",
    salesPerson2: "clearent",
    deffDownpaymentContains: false,
    downPayment: "7,680.51",
    containsDownPayment: false,
    otherThanBHPH: true,
    commissionCalculation: "0",
    commissionRate: "2.00%",
    commission: "$ 150.00",
    profitOnVehicle: "9,687.00",
    otherCalculation: "9,769.00",
    otherCommissionRate: "2.00",
    otherCommission: "$ 195.38",
    BHPH: true,
    documentaryFee: "52.00",
    salesTax: "187.50",
    governmentFee: "162.01",
    serviceContract: "0",
    dccGap: "0",
    inventoryTax: "29.00",
    totalSalesPrice: "7,680.51",
    total: "7,680.51",
    lienHolder: "qwerty",
    taxInclude: "no",
  },
  case5: {
    case: "Creating a Cash Sale by adding Service Contract and DCC/GAP",
    caseNo: "case5",
    first_name: faker.name.firstName().replace("'", ""),
    last_name: faker.name.lastName().replace("'", ""),
    phone: faker.phone.number("3##-###-####"),
    street: faker.address.street(),
    zipcode: "75901",
    full_name: "xyz",
    bhphOrOutsideFinance: false,
    sale_date: "12/12/2022",
    vehicle_price: "10,000.00",
    totalSalePrice: "11,348.01",
    finalizeSale: true,
    saleType: "cash",
    typeOfSale: 2,
    apr: "24.82",
    financeCharge: "3,195.98",
    amountFinanced: "7,890.51",
    totalOfPayments: "11,086.49",
    noOfPayments: "35",
    installmentAmount: "312.97",
    dealerTradeInOffer: "7,000.00",
    payOffLoanBalance: "2,000.00",
    cashPaidToBuyer: "2,000.00",
    actualCashValue: "8,000.00",
    tradeInContains: false,
    tradeInVehicleYear: "2000",
    tradeInVehicleVIN: "5TFUM5F12AX012971",
    tradeInStock: "",
    tradeVehicleMileage: "",
    tradeInVehiclelicensePlate: " N/A ",
    tradeInVehicleMake: " ",
    tradeInVehicleModel: " ",
    differedDate: moment().add(10, "days").format("MM/DD/YYYY"),
    differedDownPaymentAmount: "20",
    dccGapType: "DCC",
    vendorName: "qwerty",
    dccGapDealerPrice: "200",
    dccGapCostPrice: "230",
    salesPerson: "clearent",
    salesPerson2: "clearent",
    deffDownpaymentContains: false,
    downPayment: "11,348.01",
    containsDownPayment: false,
    otherThanBHPH: true,
    commissionCalculation: "0",
    commissionRate: "2.00%",
    commission: "$ 150.00",
    profitOnVehicle: "9,687.00",
    otherCalculation: "9,769.00",
    otherCommissionRate: "2.00",
    otherCommission: "$ 195.38",
    BHPH: true,
    documentaryFee: "52.00",
    salesTax: "625.00",
    governmentFee: "162.01",
    serviceContract: "250.00",
    dccGap: "230.00",
    inventoryTax: "29.00",
    totalSalesPrice: "11,348.01",
    total: "11,348.01",
    lienHolder: "qwerty",
    taxInclude: "no",
  },
  case6: {
    case: "Creating a Cash Sale by adding DCC/GAP and TradeIn",
    caseNo: "case6",
    first_name: faker.name.firstName().replace("'", ""),
    last_name: faker.name.lastName().replace("'", ""),
    phone: faker.phone.number("3##-###-####"),
    street: faker.address.street(),
    zipcode: "75901",
    full_name: "xyz",
    bhphOrOutsideFinance: false,
    sale_date: "12/12/2022",
    vehicle_price: "10,000.00",
    totalSalePrice: "7,660.51",
    finalizeSale: true,
    saleType: "cash",
    typeOfSale: 2,
    apr: "24.82",
    financeCharge: "3,195.98",
    amountFinanced: "7,890.51",
    totalOfPayments: "11,086.49",
    noOfPayments: "35",
    installmentAmount: "312.97",
    dealerTradeInOffer: "7,000.00",
    payOffLoanBalance: "2,000.00",
    cashPaidToBuyer: "2,000.00",
    actualCashValue: "8,000.00",
    tradeInContains: true,
    tradeInVehicleYear: "2000",
    tradeInVehicleVIN: "5TFUM5F12AX012971",
    tradeInStock: "",
    tradeVehicleMileage: "",
    tradeInVehiclelicensePlate: " N/A ",
    tradeInVehicleMake: " ",
    tradeInVehicleModel: " ",
    differedDate: moment().add(10, "days").format("MM/DD/YYYY"),
    differedDownPaymentAmount: "20",
    dccGapType: "DCC",
    vendorName: "qwerty",
    dccGapDealerPrice: "200",
    dccGapCostPrice: "230",
    salesPerson: "clearent",
    salesPerson2: "clearent",
    deffDownpaymentContains: false,
    downPayment: "7,660.51",
    containsDownPayment: false,
    otherThanBHPH: true,
    commissionCalculation: "0",
    commissionRate: "2.00%",
    commission: "$ 150.00",
    profitOnVehicle: "9,687.00",
    otherCalculation: "9,769.00",
    otherCommissionRate: "2.00",
    otherCommission: "$ 195.38",
    BHPH: true,
    documentaryFee: "52.00",
    salesTax: "187.50",
    governmentFee: "162.01",
    serviceContract: "0",
    dccGap: "230.00",
    inventoryTax: "29.00",
    totalSalesPrice: "7,660.51",
    total: "7,660.51",
    lienHolder: "qwerty",
    taxInclude: "no",
  },
  case7: {
    case: "Creating a BHPH sale by adding Service Contract ",
    caseNo: "case7",
    first_name: faker.name.firstName().replace("'", ""),
    last_name: faker.name.lastName().replace("'", ""),
    phone: faker.phone.number("3##-###-####"),
    street: faker.address.street(),
    zipcode: "75901",
    full_name: "xyz",
    bhphOrOutsideFinance: false,
    sale_date: "12/12/2022",
    vehicle_price: "10,000.00",
    totalSalePrice: "15,625.82",
    finalizeSale: true,
    saleType: "BHPH",
    typeOfSale: 2,
    apr: "24.82",
    financeCharge: "4,507.81",
    amountFinanced: "11,118.01",
    totalOfPayments: "15,625.82",
    noOfPayments: "35",
    installmentAmount: "440.99",
    dealerTradeInOffer: "7,000.00",
    payOffLoanBalance: "2,000.00",
    cashPaidToBuyer: "2,000.00",
    actualCashValue: "8,000.00",
    tradeInContains: false,
    tradeInVehicleYear: "2000",
    tradeInVehicleVIN: "5TFUM5F12AX012971",
    tradeInStock: "",
    tradeVehicleMileage: "",
    tradeInVehiclelicensePlate: " N/A ",
    tradeInVehicleMake: " ",
    tradeInVehicleModel: " ",
    differedDate: moment().add(10, "days").format("MM/DD/YYYY"),
    differedDownPaymentAmount: "0.00",
    dccGapType: "DCC",
    vendorName: "qwerty",
    dccGapDealerPrice: "200",
    dccGapCostPrice: "230",
    salesPerson: "clearent",
    salesPerson2: "aswe",
    deffDownpaymentContains: false,
    downPayment: "0",
    containsDownPayment: false,
    otherThanBHPH: false,
    commissionCalculation: "0",
    commissionRate: "1.50%",
    commission: "$ 150.00",
    profitOnVehicle: " ",
    otherCalculation: " ",
    otherCommissionRate: " ",
    otherCommission: "$ 150",
    BHPH: true,
    documentaryFee: "52.00",
    salesTax: "625.00",
    governmentFee: "162.01",
    serviceContract: "250.00",
    dccGap: "0.00",
    inventoryTax: "29.00",
    totalSalesPrice: "11,118.01",
    total: "15,625.82",
    lienHolder: "qwerty",
    taxInclude: "no",
    salesTaxMonthly: "0",
    person1: true,
    person2: false,
  },
  case8: {
    case: "Creating a BHPH Sale by adding DCC/GAP",
    caseNo: "case8",
    first_name: faker.name.firstName().replace("'", ""),
    last_name: faker.name.lastName().replace("'", ""),
    phone: faker.phone.number("3##-###-####"),
    street: faker.address.street(),
    zipcode: "75901",
    full_name: "xyz",
    bhphOrOutsideFinance: false,
    sale_date: "12/12/2022",
    vehicle_price: "10,000.00",
    totalSalePrice: "15,597.66",
    finalizeSale: true,
    saleType: "BHPH",
    typeOfSale: 2,
    apr: "24.82",
    financeCharge: "4,499.65",
    amountFinanced: "11,098.01",
    totalOfPayments: "15,597.66",
    noOfPayments: "35",
    installmentAmount: "440.20",
    dealerTradeInOffer: "7,000.00",
    payOffLoanBalance: "2,000.00",
    cashPaidToBuyer: "2,000.00",
    actualCashValue: "8,000.00",
    tradeInContains: false,
    tradeInVehicleYear: "2000",
    tradeInVehicleVIN: "5TFUM5F12AX012971",
    tradeInStock: "",
    tradeVehicleMileage: "",
    tradeInVehiclelicensePlate: " N/A ",
    tradeInVehicleMake: " ",
    tradeInVehicleModel: " ",
    differedDate: moment().add(10, "days").format("MM/DD/YYYY"),
    differedDownPaymentAmount: "0.00",
    dccGapType: "DCC",
    vendorName: "qwerty",
    dccGapDealerPrice: "200",
    dccGapCostPrice: "230",
    salesPerson: "clearent",
    salesPerson2: "aswe",
    deffDownpaymentContains: false,
    downPayment: "0",
    containsDownPayment: false,
    otherThanBHPH: false,
    commissionCalculation: "0",
    commissionRate: "1.50%",
    commission: "$ 150.00",
    profitOnVehicle: " ",
    otherCalculation: " ",
    otherCommissionRate: " ",
    otherCommission: "$ 150",
    BHPH: true,
    documentaryFee: "52.00",
    salesTax: "625.00",
    governmentFee: "162.01",
    serviceContract: "0.00",
    dccGap: "230.00",
    inventoryTax: "29.00",
    totalSalesPrice: "11,098.01",
    total: "15,597.66",
    lienHolder: "qwerty",
    taxInclude: "no",
    salesTaxMonthly: "0",
    person1: true,
    person2: false,
  },
  case9: {
    case: "Creating a BHPH Sale by adding TradeIn",
    caseNo: "case9",
    first_name: faker.name.firstName().replace("'", ""),
    last_name: faker.name.lastName().replace("'", ""),
    phone: faker.phone.number("3##-###-####"),
    street: faker.address.street(),
    zipcode: "75901",
    full_name: "xyz",
    bhphOrOutsideFinance: false,
    sale_date: "12/12/2022",
    vehicle_price: "10,000.00",
    totalSalePrice: "10,443.17",
    finalizeSale: true,
    saleType: "BHPH",
    typeOfSale: 2,
    apr: "24.82",
    financeCharge: "3,012.66",
    amountFinanced: "7,430.51",
    totalOfPayments: "10,443.17",
    noOfPayments: "35",
    installmentAmount: "294.73",
    dealerTradeInOffer: "7,000.00",
    payOffLoanBalance: "2,000.00",
    cashPaidToBuyer: "2,000.00",
    actualCashValue: "8,000.00",
    tradeInContains: true,
    tradeInVehicleYear: "2000",
    tradeInVehicleVIN: "5TFUM5F12AX012971",
    tradeInStock: "",
    tradeVehicleMileage: "",
    tradeInVehiclelicensePlate: " N/A ",
    tradeInVehicleMake: " ",
    tradeInVehicleModel: " ",
    differedDate: moment().add(10, "days").format("MM/DD/YYYY"),
    differedDownPaymentAmount: "0.00",
    dccGapType: "DCC",
    vendorName: "qwerty",
    dccGapDealerPrice: "200",
    dccGapCostPrice: "230",
    salesPerson: "clearent",
    salesPerson2: "aswe",
    deffDownpaymentContains: false,
    downPayment: "0",
    containsDownPayment: false,
    otherThanBHPH: false,
    commissionCalculation: "0",
    commissionRate: "1.50%",
    commission: "$ 150.00",
    profitOnVehicle: " ",
    otherCalculation: " ",
    otherCommissionRate: " ",
    otherCommission: "$ 150",
    BHPH: true,
    documentaryFee: "52.00",
    salesTax: "187.50",
    governmentFee: "162.01",
    serviceContract: "0.00",
    dccGap: "0.00",
    inventoryTax: "29.00",
    totalSalesPrice: "7,430.51",
    total: "10,443.17",
    lienHolder: "qwerty",
    taxInclude: "no",
    salesTaxMonthly: "0",
    person1: true,
    person2: false,
  },
  case10: {
    case: "Adding new lien holder for outside sale",
    caseNo: "case10",
    first_name: faker.name.firstName().replace("'", ""),
    last_name: faker.name.lastName().replace("'", ""),
    phone: faker.phone.number("3##-###-####"),
    street: faker.address.street(),
    zipcode: "75901",
    full_name: "xyz",
    bhphOrOutsideFinance: false,
    sale_date: "12/12/2022",
    vehicle_price: "10,000.00",
    totalSalePrice: "15,274.35",
    finalizeSale: true,
    saleType: "OutsideFinance",
    typeOfSale: 1,
    apr: "24.82",
    financeCharge: "4,406.34",
    amountFinanced: "10,868.01",
    totalOfPayments: "15,274.35",
    noOfPayments: "35",
    installmentAmount: "431.08",
    dealerTradeInOffer: "7,000.00",
    payOffLoanBalance: "2,000.00",
    cashPaidToBuyer: "2,000.00",
    actualCashValue: "8,000.00",
    tradeInContains: false,
    tradeInVehicleYear: "2000",
    tradeInVehicleVIN: "5TFUM5F12AX012971",
    tradeInStock: "",
    tradeVehicleMileage: "",
    tradeInVehiclelicensePlate: " N/A ",
    tradeInVehicleMake: " ",
    tradeInVehicleModel: " ",
    differedDate: moment().add(10, "days").format("MM/DD/YYYY"),
    differedDownPaymentAmount: "0.00",
    dccGapType: "DCC",
    vendorName: "qwerty",
    dccGapDealerPrice: "200",
    dccGapCostPrice: "230",
    salesPerson: "clearent",
    salesPerson2: "aswe",
    deffDownpaymentContains: false,
    downPayment: "0",
    containsDownPayment: false,
    otherThanBHPH: false,
    commissionCalculation: "0",
    commissionRate: "1.50%",
    commission: "$ 150.00",
    profitOnVehicle: " ",
    otherCalculation: " ",
    otherCommissionRate: " ",
    otherCommission: "$ 150",
    BHPH: true,
    documentaryFee: "52.00",
    salesTax: "625.00",
    governmentFee: "162.01",
    serviceContract: "0.00",
    dccGap: "0.00",
    inventoryTax: "29.00",
    totalSalesPrice: "10,868.01",
    total: "15,274.35",
    taxInclude: "no",
    salesTaxMonthly: "0",
    randomName: faker.name.firstName().replace("'", ""),
    person1: true,
    person2: false,
    lienHolder: faker.name.firstName().replace("'", ""),
  },
  case11: {
    case: "new lien holder for outside sale, finance charge rate participation, with flat rate",
    caseNo: "case11",
    first_name: faker.name.firstName().replace("'", ""),
    last_name: faker.name.lastName().replace("'", ""),
    phone: faker.phone.number("3##-###-####"),
    street: faker.address.street(),
    zipcode: "75901",
    full_name: "xyz",
    bhphOrOutsideFinance: false,
    sale_date: "12/12/2022",
    vehicle_price: "10,000.00",
    totalSalePrice: "15,274.35",
    finalizeSale: true,
    saleType: "OutsideFinance",
    typeOfSale: 1,
    apr: "24.82",
    financeCharge: "4,406.34",
    amountFinanced: "10,868.01",
    totalOfPayments: "15,274.35",
    noOfPayments: "35",
    installmentAmount: "431.08",
    dealerTradeInOffer: "0.00",
    payOffLoanBalance: "0.00",
    cashPaidToBuyer: "2,000.00",
    actualCashValue: "0.00",
    tradeInContains: false,
    tradeInVehicleYear: "2000",
    tradeInVehicleVIN: "5TFUM5F12AX012971",
    tradeInStock: "",
    tradeVehicleMileage: "",
    tradeInVehiclelicensePlate: " N/A ",
    tradeInVehicleMake: " ",
    tradeInVehicleModel: " ",
    differedDate: moment().add(10, "days").format("MM/DD/YYYY"),
    differedDownPaymentAmount: "0.00",
    dccGapType: "DCC",
    vendorName: "qwerty",
    dccGapDealerPrice: "0.00",
    dccGapCostPrice: "0.00",
    salesPerson: "clearent",
    salesPerson2: "clearent",
    deffDownpaymentContains: false,
    downPayment: "0",
    containsDownPayment: false,
    otherThanBHPH: false,
    commissionCalculation: "0",
    commissionRate: "1.50%",
    commission: "$ 150.00",
    profitOnVehicle: " ",
    otherCalculation: " ",
    otherCommissionRate: " ",
    otherCommission: "$ 150",
    BHPH: true,
    documentaryFee: "52.00",
    salesTax: "625.00",
    governmentFee: "162.01",
    serviceContract: "0.00",
    dccGap: "0.00",
    inventoryTax: "29.00",
    totalSalesPrice: "10,868.01",
    total: "15,274.35",
    taxInclude: "no",
    salesTaxMonthly: "0",
    randomName: faker.name.firstName().replace("'", ""),
    person1: true,
    person2: false,
    feeDealer: 100,
    amountEarned: 1200,
    buyRateFromBank: 10,
    bankPercentHoldInReserve: 50,
    netSellingPrice: "10,000.00",
    totalDownPayment: "0.00",
    totalOfTaxAndFee: "868.01",
    dccGapProfit: "0.00",
    oneLien: true,
    lienHolder: "Testone",
  },
  case12: {
    case: "finance charge rate participation",
    caseNo: "case12",
    first_name: faker.name.firstName().replace("'", ""),
    last_name: faker.name.lastName().replace("'", ""),
    phone: faker.phone.number("3##-###-####"),
    street: faker.address.street(),
    zipcode: "75901",
    full_name: "xyz",
    bhphOrOutsideFinance: false,
    sale_date: "12/12/2022",
    vehicle_price: "10,000.00",
    totalSalePrice: "15,274.35",
    finalizeSale: true,
    saleType: "OutsideFinance",
    typeOfSale: 1,
    apr: "24.82",
    financeCharge: "4,406.34",
    amountFinanced: "10,868.01",
    totalOfPayments: "15,274.35",
    noOfPayments: "35",
    installmentAmount: "431.08",
    dealerTradeInOffer: "0.00",
    payOffLoanBalance: "0.00",
    cashPaidToBuyer: "2,000.00",
    actualCashValue: "0.00",
    tradeInContains: false,
    tradeInVehicleYear: "2000",
    tradeInVehicleVIN: "5TFUM5F12AX012971",
    tradeInStock: "",
    tradeVehicleMileage: "",
    tradeInVehiclelicensePlate: " N/A ",
    tradeInVehicleMake: " ",
    tradeInVehicleModel: " ",
    differedDate: moment().add(10, "days").format("MM/DD/YYYY"),
    differedDownPaymentAmount: "0.00",
    dccGapType: "DCC",
    vendorName: "qwerty",
    dccGapDealerPrice: "0.00",
    dccGapCostPrice: "0.00",
    salesPerson: "clearent",
    salesPerson2: "clearent",
    deffDownpaymentContains: false,
    downPayment: "0",
    containsDownPayment: false,
    otherThanBHPH: false,
    commissionCalculation: "0",
    commissionRate: "1.50%",
    commission: "$ 150.00",
    profitOnVehicle: " ",
    otherCalculation: " ",
    otherCommissionRate: " ",
    otherCommission: "$ 150",
    BHPH: true,
    documentaryFee: "52.00",
    salesTax: "625.00",
    governmentFee: "162.01",
    serviceContract: "0.00",
    dccGap: "0.00",
    inventoryTax: "29.00",
    totalSalesPrice: "10,868.01",
    total: "15,274.35",
    taxInclude: "no",
    salesTaxMonthly: "0",
    randomName: faker.name.firstName().replace("'", ""),
    person1: true,
    person2: false,
    feeDealer: 100,
    amountEarned: 1200,
    buyRateFromBank: 10,
    bankPercentHoldInReserve: 50,
    netSellingPrice: "10,000.00",
    totalDownPayment: "0.00",
    totalOfTaxAndFee: "868.01",
    dccGapProfit: "0.00",
    lienHolder: "Testone",
    oneLien: true,
    secLien: false,
  },
  case13: {
    case: "sale details page by adding TradeIn, changing sale type to bhph",
    caseNo: "case13",
    first_name: faker.name.firstName().replace("'", ""),
    last_name: faker.name.lastName().replace("'", ""),
    phone: faker.phone.number("3##-###-####"),
    street: faker.address.street(),
    zipcode: "75901",
    full_name: "xyz",
    bhphOrOutsideFinance: true,
    sale_date: "12/12/2022",
    vehicle_price: "10,000.00",
    totalSalePrice: "10,443.17",
    finalizeSale: true,
    saleType: "BHPH",
    typeOfSale: 2,
    apr: "24.82",
    financeCharge: "3,012.66",
    amountFinanced: "7,430.51",
    totalOfPayments: "10,443.17",
    noOfPayments: "35",
    installmentAmount: "294.73",
    dealerTradeInOffer: "7,000.00",
    payOffLoanBalance: "2,000.00",
    cashPaidToBuyer: "2,000.00",
    actualCashValue: "8,000.00",
    tradeInContains: true,
    tradeInVehicleYear: "2000",
    tradeInVehicleVIN: "5TFUM5F12AX012971",
    tradeInStock: "",
    tradeVehicleMileage: "",
    tradeInVehiclelicensePlate: " N/A ",
    tradeInVehicleMake: " ",
    tradeInVehicleModel: " ",
    differedDate: moment().add(10, "days").format("MM/DD/YYYY"),
    differedDownPaymentAmount: "0.00",
    dccGapType: "DCC",
    vendorName: "qwerty",
    dccGapDealerPrice: "200",
    dccGapCostPrice: "230",
    salesPerson: "clearent",
    salesPerson2: "clearent",
    deffDownpaymentContains: false,
    downPayment: "0.00",
    containsDownPayment: false,
    otherThanBHPH: true,
    commissionCalculation: "0",
    commissionRate: "2.00%",
    commission: "$ 150.00",
    profitOnVehicle: "9,687.00",
    otherCalculation: "9,769.00",
    otherCommissionRate: "2.00",
    otherCommission: "$ 195.38",
    BHPH: true,
    documentaryFee: "52.00",
    salesTax: "187.50",
    governmentFee: "162.01",
    serviceContract: "0",
    dccGap: "0",
    inventoryTax: "29.00",
    totalSalesPrice: "7,430.51",
    total: "10,443.17",
    lienHolder: "Testone",
    taxInclude: "no",
    jointCustomer: false,
    accountType: "BHPH",
    deputyServiceFee: "15.00",
    netTradeIn: "3,000.00",
    otherFees: "0.00",
    totalGovernmentFee: "243.01",
    totalQuotePrice: "7,430.51",
    ifSaleDetails: true,
    ifAccountNumber: false,
  },
  case14: {
    case: "joint sale details page by adding TradeIn, changing sale type to bhph",
    caseNo: "case14",
    first_name: faker.name.firstName().replace("'", ""),
    last_name: faker.name.lastName().replace("'", ""),
    phone: faker.phone.number("3##-###-####"),
    street: faker.address.street(),
    zipcode: "75901",
    full_name: "xyz",
    bhphOrOutsideFinance: true,
    sale_date: "12/12/2022",
    vehicle_price: "10,000.00",
    totalSalePrice: "10,443.17",
    finalizeSale: true,
    saleType: "BHPH",
    typeOfSale: 2,
    apr: "24.82",
    financeCharge: "3,012.66",
    amountFinanced: "7,430.51",
    totalOfPayments: "10,443.17",
    noOfPayments: "35",
    installmentAmount: "294.73",
    dealerTradeInOffer: "7,000.00",
    payOffLoanBalance: "2,000.00",
    cashPaidToBuyer: "2,000.00",
    actualCashValue: "8,000.00",
    tradeInContains: true,
    tradeInVehicleYear: "2000",
    tradeInVehicleVIN: "5TFUM5F12AX012971",
    tradeInStock: "",
    tradeVehicleMileage: "",
    tradeInVehiclelicensePlate: " N/A ",
    tradeInVehicleMake: " ",
    tradeInVehicleModel: " ",
    differedDate: moment().add(10, "days").format("MM/DD/YYYY"),
    differedDownPaymentAmount: "0.00",
    dccGapType: "DCC",
    vendorName: "qwerty",
    dccGapDealerPrice: "200",
    dccGapCostPrice: "230",
    salesPerson: "clearent",
    salesPerson2: "clearent",
    deffDownpaymentContains: false,
    downPayment: "0.00",
    containsDownPayment: false,
    otherThanBHPH: true,
    commissionCalculation: "0",
    commissionRate: "2.00%",
    commission: "$ 150.00",
    profitOnVehicle: "9,687.00",
    otherCalculation: "9,769.00",
    otherCommissionRate: "2.00",
    otherCommission: "$ 195.38",
    BHPH: true,
    documentaryFee: "52.00",
    salesTax: "187.50",
    governmentFee: "162.01",
    serviceContract: "0",
    dccGap: "0",
    inventoryTax: "29.00",
    totalSalesPrice: "7,430.51",
    total: "10,443.17",
    lienHolder: "qwerty",
    taxInclude: "no",
    jointCustomer: true,
    accountType: "BHPH",
    deputyServiceFee: "15.00",
    netTradeIn: "3,000.00",
    otherFees: "0.00",
    totalGovernmentFee: "243.01",
    totalQuotePrice: "7,430.51",
    sec_first_name: faker.name.firstName().replace("'", ""),
    sec_last_name: faker.name.lastName().replace("'", ""),
    sec_phone: faker.phone.number("3##-###-####"),
    sec_street: faker.address.street(),
    sec_zipcode: "75901",
    ifSaleDetails: true,
    ifAccountNumber: false,
  },
  case15: {
    case: "Adding both lien holders for outside sale",
    caseNo: "case15",
    first_name: faker.name.firstName().replace("'", ""),
    last_name: faker.name.lastName().replace("'", ""),
    phone: faker.phone.number("3##-###-####"),
    street: faker.address.street(),
    zipcode: "75901",
    full_name: "xyz",
    bhphOrOutsideFinance: false,
    sale_date: "12/12/2022",
    vehicle_price: "10,000.00",
    totalSalePrice: "15,274.35",
    finalizeSale: true,
    saleType: "OutsideFinance",
    typeOfSale: 1,
    apr: "24.82",
    financeCharge: "4,406.34",
    amountFinanced: "10,868.01",
    totalOfPayments: "15,274.35",
    noOfPayments: "35",
    installmentAmount: "431.08",
    dealerTradeInOffer: "0.00",
    payOffLoanBalance: "0.00",
    cashPaidToBuyer: "2,000.00",
    actualCashValue: "0.00",
    tradeInContains: false,
    tradeInVehicleYear: "2000",
    tradeInVehicleVIN: "5TFUM5F12AX012971",
    tradeInStock: "",
    tradeVehicleMileage: "",
    tradeInVehiclelicensePlate: " N/A ",
    tradeInVehicleMake: " ",
    tradeInVehicleModel: " ",
    differedDate: moment().add(10, "days").format("MM/DD/YYYY"),
    differedDownPaymentAmount: "0.00",
    dccGapType: "DCC",
    vendorName: "qwerty",
    dccGapDealerPrice: "0.00",
    dccGapCostPrice: "0.00",
    salesPerson: "clearent",
    salesPerson2: "aswe",
    deffDownpaymentContains: false,
    downPayment: "0",
    containsDownPayment: false,
    otherThanBHPH: false,
    commissionCalculation: "0",
    commissionRate: "1.50%",
    commission: "$ 150.00",
    profitOnVehicle: " ",
    otherCalculation: " ",
    otherCommissionRate: " ",
    otherCommission: "$ 150",
    BHPH: true,
    documentaryFee: "52.00",
    salesTax: "625.00",
    governmentFee: "162.01",
    serviceContract: "0.00",
    dccGap: "0.00",
    inventoryTax: "29.00",
    totalSalesPrice: "10,868.01",
    total: "15,274.35",
    taxInclude: "no",
    salesTaxMonthly: "0",
    lienHolder: "Testone",
    addLienHolder: "Testtwo",
    oneLien: true,
    secLien: true,
    netSellingPrice: "10,000.00",
    totalDownPayment: "0.00",
    totalOfTaxAndFee: "868.01",
    dccGapProfit: "0.00",
  },
  case16: {
    case: "Creating a cash Sale and checking recent deals",
    caseNo: "case16",
    first_name: faker.name.firstName().replace("'", ""),
    last_name: faker.name.lastName().replace("'", ""),
    phone: faker.phone.number("3##-###-####"),
    street: faker.address.street(),
    zipcode: "75901",
    full_name: "xyz",
    bhphOrOutsideFinance: false,
    sale_date: "12/12/2022",
    vehicle_price: "10,000.00",
    totalSalePrice: "10,868.01",
    finalizeSale: true,
    saleType: "cash",
    typeOfSale: 0,
    apr: "24.82",
    financeCharge: "3,195.98",
    amountFinanced: "7,890.51",
    totalOfPayments: "11,086.49",
    noOfPayments: "35",
    installmentAmount: "312.97",
    dealerTradeInOffer: "0.00",
    payOffLoanBalance: "0.00",
    cashPaidToBuyer: "0.00",
    actualCashValue: "0.00",
    tradeInContains: false,
    tradeInVehicleYear: "2000",
    tradeInVehicleVIN: "5TFUM5F12AX012971",
    tradeInStock: "",
    tradeVehicleMileage: "",
    tradeInVehiclelicensePlate: " N/A ",
    tradeInVehicleMake: " ",
    tradeInVehicleModel: " ",
    differedDate: moment().add(10, "days").format("MM/DD/YYYY"),
    differedDownPaymentAmount: "20",
    dccGapType: "DCC",
    vendorName: "qwerty",
    dccGapDealerPrice: "200",
    dccGapCostPrice: "230",
    salesPerson: "clearent",
    salesPerson2: "clearent",
    deffDownpaymentContains: false,
    downPayment: "10,868.01",
    containsDownPayment: false,
    otherThanBHPH: true,
    commissionCalculation: "0",
    commissionRate: "2.00%",
    commission: "$ 150.00",
    profitOnVehicle: "9,687.00",
    otherCalculation: "9,769.00",
    otherCommissionRate: "2.00",
    otherCommission: "$ 195.38",
    BHPH: true,
    documentaryFee: "52.00",
    salesTax: "625.00",
    governmentFee: "162.01",
    serviceContract: "0",
    dccGap: "0.00",
    inventoryTax: "29.00",
    totalSalesPrice: "11,098.01",
    total: "11,098.01",
    lienHolder: "qwerty",
    taxInclude: "no",
    ifSaleDetails: true,
    ifAccountNumber: false,
    jointCustomer: false,
    accountType: "CASH",
    deputyServiceFee: "15.00",
    netTradeIn: "0.00",
    otherFees: "0.00",
    totalGovernmentFee: "243.01",
    totalQuotePrice: "10,868.01",
    checkSalesPrice: true,
  },
  case17: {
    case: "Creating a cash sale and changing mileage",
    caseNo: "case17",
    first_name: faker.name.firstName().replace("'", ""),
    last_name: faker.name.lastName().replace("'", ""),
    phone: faker.phone.number("3##-###-####"),
    street: faker.address.street(),
    zipcode: "75901",
    full_name: "xyz",
    bhphOrOutsideFinance: false,
    sale_date: "12/12/2022",
    vehicle_price: "10,000.00",
    totalSalePrice: "10,868.01",
    finalizeSale: true,
    saleType: "cash",
    typeOfSale: 0,
    apr: "24.82",
    financeCharge: "3,195.98",
    amountFinanced: "7,890.51",
    totalOfPayments: "11,086.49",
    noOfPayments: "35",
    installmentAmount: "312.97",
    dealerTradeInOffer: "0.00",
    payOffLoanBalance: "0.00",
    cashPaidToBuyer: "0.00",
    actualCashValue: "0.00",
    tradeInContains: false,
    tradeInVehicleYear: "2000",
    tradeInVehicleVIN: "5TFUM5F12AX012971",
    tradeInStock: "",
    tradeVehicleMileage: "",
    tradeInVehiclelicensePlate: " N/A ",
    tradeInVehicleMake: " ",
    tradeInVehicleModel: " ",
    differedDate: moment().add(10, "days").format("MM/DD/YYYY"),
    differedDownPaymentAmount: "20",
    dccGapType: "DCC",
    vendorName: "qwerty",
    dccGapDealerPrice: "200",
    dccGapCostPrice: "230",
    salesPerson: "clearent",
    salesPerson2: "clearent",
    deffDownpaymentContains: false,
    downPayment: "10,868.01",
    containsDownPayment: false,
    otherThanBHPH: true,
    commissionCalculation: "0",
    commissionRate: "2.00%",
    commission: "$ 150.00",
    profitOnVehicle: "9,687.00",
    otherCalculation: "9,769.00",
    otherCommissionRate: "2.00",
    otherCommission: "$ 195.38",
    BHPH: true,
    documentaryFee: "52.00",
    salesTax: "625.00",
    governmentFee: "162.01",
    serviceContract: "0",
    dccGap: "230.00",
    inventoryTax: "29.00",
    totalSalesPrice: "11,098.01",
    total: "11,098.01",
    lienHolder: "qwerty",
    taxInclude: "no",
    ifSaleDetails: true,
    ifAccountNumber: false,
    jointCustomer: false,
    accountType: "CASH",
    deputyServiceFee: "15.00",
    netTradeIn: "0.00",
    otherFees: "0.00",
    totalGovernmentFee: "243.01",
    totalQuotePrice: "11,098.01",
    mileage: 2450,
    checkSalesPrice: true,
  },
  case18: {
    case: "Adding new lien holder to cash sale",
    caseNo: "case18",
    first_name: faker.name.firstName().replace("'", ""),
    last_name: faker.name.lastName().replace("'", ""),
    phone: faker.phone.number("3##-###-####"),
    street: faker.address.street(),
    zipcode: "75901",
    full_name: "xyz",
    bhphOrOutsideFinance: false,
    sale_date: "12/12/2022",
    vehicle_price: "10,000.00",
    totalSalePrice: "10,868.01",
    finalizeSale: true,
    saleType: "cash",
    typeOfSale: 0,
    apr: "24.82",
    financeCharge: "3,195.98",
    amountFinanced: "7,890.51",
    totalOfPayments: "11,086.49",
    noOfPayments: "35",
    installmentAmount: "312.97",
    dealerTradeInOffer: "0.00",
    payOffLoanBalance: "0.00",
    cashPaidToBuyer: "0.00",
    actualCashValue: "0.00",
    tradeInContains: false,
    tradeInVehicleYear: "2000",
    tradeInVehicleVIN: "5TFUM5F12AX012971",
    tradeInStock: "",
    tradeVehicleMileage: "",
    tradeInVehiclelicensePlate: " N/A ",
    tradeInVehicleMake: " ",
    tradeInVehicleModel: " ",
    differedDate: moment().add(10, "days").format("MM/DD/YYYY"),
    differedDownPaymentAmount: "20",
    dccGapType: "DCC",
    vendorName: "qwerty",
    dccGapDealerPrice: "200",
    dccGapCostPrice: "230",
    salesPerson: "clearent",
    salesPerson2: "clearent",
    deffDownpaymentContains: false,
    downPayment: "11,098.01",
    containsDownPayment: false,
    otherThanBHPH: true,
    commissionCalculation: "0",
    commissionRate: "2.00%",
    commission: "$ 150.00",
    profitOnVehicle: "9,687.00",
    otherCalculation: "9,769.00",
    otherCommissionRate: "2.00",
    otherCommission: "$ 195.38",
    BHPH: true,
    documentaryFee: "52.00",
    salesTax: "625.00",
    governmentFee: "162.01",
    serviceContract: "0",
    dccGap: "230.00",
    inventoryTax: "29.00",
    totalSalesPrice: "11,098.01",
    total: "11,098.01",
    lienHolder: "qwerty",
    taxInclude: "no",
    randomName: faker.name.firstName().replace("'", ""),
    person1: true,
    person2: false,
    lienHolder: faker.name.firstName().replace("'", ""),
    checkSalesPrice: true,
  },
  case19: {
    case: "Validating Interest Rate",
    caseNo: "case19",
    first_name: faker.name.firstName().replace("'", ""),
    last_name: faker.name.lastName().replace("'", ""),
    phone: faker.phone.number("3##-###-####"),
    street: faker.address.street(),
    zipcode: "75901",
    full_name: "xyz",
    bhphOrOutsideFinance: false,
    sale_date: "12/12/2022",
    vehicle_price: "10,000.00",
    totalSalePrice: "15,274.35",
    finalizeSale: true,
    saleType: "BHPH",
    typeOfSale: 2,
    apr: "24.82",
    terms: "36",
    financeCharge: "4,406.34",
    amountFinanced: "10,868.01",
    totalOfPayments: "15,274.35",
    noOfPayments: "35",
    installmentAmount: "431.08",
    dealerTradeInOffer: "7,000.00",
    payOffLoanBalance: "2,000.00",
    cashPaidToBuyer: "2,000.00",
    actualCashValue: "8,000.00",
    tradeInContains: false,
    tradeInVehicleYear: "2000",
    tradeInVehicleVIN: "5TFUM5F12AX012971",
    tradeInStock: "",
    tradeVehicleMileage: "",
    tradeInVehiclelicensePlate: " N/A ",
    tradeInVehicleMake: " ",
    tradeInVehicleModel: " ",
    differedDate: moment().add(10, "days").format("MM/DD/YYYY"),
    differedDownPaymentAmount: "0.00",
    dccGapType: "DCC",
    vendorName: "qwerty",
    dccGapDealerPrice: "200",
    dccGapCostPrice: "230",
    salesPerson: "clearent",
    salesPerson2: "aswe",
    deffDownpaymentContains: false,
    downPayment: "0",
    containsDownPayment: false,
    otherThanBHPH: false,
    commissionCalculation: "0",
    commissionRate: "1.50%",
    commission: "$ 150.00",
    profitOnVehicle: " ",
    otherCalculation: " ",
    otherCommissionRate: " ",
    otherCommission: "$ 150",
    BHPH: true,
    documentaryFee: "52.00",
    salesTax: "625.00",
    governmentFee: "162.01",
    serviceContract: "0.00",
    dccGap: "0.00",
    inventoryTax: "29.00",
    totalSalesPrice: "10,868.01",
    total: "15,274.35",
    taxInclude: "no",
    salesTaxMonthly: "0",
  },
  case20: {
    case: "validating Sales tax and govt fee",
    caseNo: "case20",
    first_name: faker.name.firstName().replace("'", ""),
    last_name: faker.name.lastName().replace("'", ""),
    phone: faker.phone.number("3##-###-####"),
    street: faker.address.street(),
    zipcode: "75901",
    full_name: "xyz",
    bhphOrOutsideFinance: false,
    sale_date: "12/12/2022",
    vehicle_price: "10,000.00",
    totalSalePrice: "15,274.35",
    finalizeSale: true,
    saleType: "BHPH",
    typeOfSale: 2,
    apr: "24.82",
    financeCharge: "4,406.34",
    amountFinanced: "10,868.01",
    totalOfPayments: "15,274.35",
    noOfPayments: "35",
    installmentAmount: "431.08",
    dealerTradeInOffer: "7,000.00",
    payOffLoanBalance: "2,000.00",
    cashPaidToBuyer: "2,000.00",
    actualCashValue: "8,000.00",
    tradeInContains: false,
    tradeInVehicleYear: "2000",
    tradeInVehicleVIN: "5TFUM5F12AX012971",
    tradeInStock: "",
    tradeVehicleMileage: "",
    tradeInVehiclelicensePlate: " N/A ",
    tradeInVehicleMake: " ",
    tradeInVehicleModel: " ",
    differedDate: moment().add(10, "days").format("MM/DD/YYYY"),
    differedDownPaymentAmount: "0.00",
    dccGapType: "DCC",
    vendorName: "qwerty",
    dccGapDealerPrice: "200",
    dccGapCostPrice: "230",
    salesPerson: "clearent",
    salesPerson2: "aswe",
    deffDownpaymentContains: false,
    downPayment: "0",
    containsDownPayment: false,
    otherThanBHPH: false,
    commissionCalculation: "0",
    commissionRate: "1.50%",
    commission: "$ 150.00",
    profitOnVehicle: " ",
    otherCalculation: " ",
    otherCommissionRate: " ",
    otherCommission: "$ 150",
    BHPH: true,
    documentaryFee: "52.00",
    salesTax: "625.00",
    governmentFee: "162.01",
    serviceContract: "0.00",
    dccGap: "0.00",
    inventoryTax: "29.00",
    totalSalesPrice: "10,868.01",
    total: "15,274.35",
    taxInclude: "no",
    salesTaxMonthly: "0",
  },
  case21: {
    case: "Cancel and continue the deal",
    caseNo: "case21",
    first_name: faker.name.firstName().replace("'", ""),
    last_name: faker.name.lastName().replace("'", ""),
    phone: faker.phone.number("3##-###-####"),
    street: faker.address.street(),
    zipcode: "75901",
    full_name: "xyz",
    bhphOrOutsideFinance: true,
    sale_date: "12/12/2022",
    vehicle_price: "10,000.00",
    totalSalePrice: "15,274.35",
    finalizeSale: true,
    saleType: "BHPH",
    typeOfSale: 2,
    apr: "24.82",
    terms: "36",
    financeCharge: "4,406.34",
    amountFinanced: "10,868.01",
    totalOfPayments: "15,274.35",
    noOfPayments: "35",
    installmentAmount: "431.08",
    dealerTradeInOffer: "7,000.00",
    payOffLoanBalance: "2,000.00",
    cashPaidToBuyer: "2,000.00",
    actualCashValue: "8,000.00",
    tradeInContains: false,
    tradeInVehicleYear: "2000",
    tradeInVehicleVIN: "5TFUM5F12AX012971",
    tradeInStock: "",
    tradeVehicleMileage: "",
    tradeInVehiclelicensePlate: " N/A ",
    tradeInVehicleMake: " ",
    tradeInVehicleModel: " ",
    differedDate: moment().add(10, "days").format("MM/DD/YYYY"),
    differedDownPaymentAmount: "0.00",
    dccGapType: "DCC",
    vendorName: "qwerty",
    dccGapDealerPrice: "200",
    dccGapCostPrice: "230",
    salesPerson: "clearent",
    salesPerson2: "aswe",
    deffDownpaymentContains: false,
    downPayment: "0",
    containsDownPayment: false,
    otherThanBHPH: false,
    commissionCalculation: "0",
    commissionRate: "1.50%",
    commission: "$ 150.00",
    profitOnVehicle: " ",
    otherCalculation: " ",
    otherCommissionRate: " ",
    otherCommission: "$ 150",
    BHPH: true,
    documentaryFee: "52.00",
    salesTax: "625.00",
    governmentFee: "162.01",
    serviceContract: "0.00",
    dccGap: "0.00",
    inventoryTax: "29.00",
    totalSalesPrice: "10,868.01",
    total: "15,274.35",
    taxInclude: "no",
    salesTaxMonthly: "0",
  },
  case22: {
    case: "Change firstpayment date and complete the sale  ",
    caseNo: "case22",
    first_name: faker.name.firstName().replace("'", ""),
    last_name: faker.name.lastName().replace("'", ""),
    phone: faker.phone.number("3##-###-####"),
    street: faker.address.street(),
    zipcode: "75901",
    full_name: "xyz",
    bhphOrOutsideFinance: false,
    sale_date: "12/12/2022",
    vehicle_price: "10,000.00",
    totalSalePrice: "15,634.79",
    finalizeSale: true,
    saleType: "BHPH",
    typeOfSale: 2,
    apr: "24.82",
    financeCharge: "4,766.78",
    amountFinanced: "10,868.01",
    totalOfPayments: "15,634.79",
    noOfPayments: "35",
    installmentAmount: "",
    dealerTradeInOffer: "7,000.00",
    payOffLoanBalance: "2,000.00",
    cashPaidToBuyer: "2,000.00",
    actualCashValue: "8,000.00",
    tradeInContains: false,
    tradeInVehicleYear: "2000",
    tradeInVehicleVIN: "5TFUM5F12AX012971",
    tradeInStock: "",
    tradeVehicleMileage: "",
    tradeInVehiclelicensePlate: " N/A ",
    tradeInVehicleMake: " ",
    tradeInVehicleModel: " ",
    differedDate: moment().add(10, "days").format("MM/DD/YYYY"),
    differedDownPaymentAmount: "0.00",
    dccGapType: "DCC",
    vendorName: "qwerty",
    dccGapDealerPrice: "200",
    dccGapCostPrice: "230",
    salesPerson: "clearent",
    salesPerson2: "aswe",
    deffDownpaymentContains: false,
    downPayment: "0",
    containsDownPayment: false,
    otherThanBHPH: false,
    commissionCalculation: "0",
    commissionRate: "1.50%",
    commission: "$ 150.00",
    profitOnVehicle: " ",
    otherCalculation: " ",
    otherCommissionRate: " ",
    otherCommission: "$ 150",
    BHPH: true,
    documentaryFee: "52.00",
    salesTax: "625.00",
    governmentFee: "162.01",
    serviceContract: "250.00",
    dccGap: "0.00",
    inventoryTax: "29.00",
    totalSalesPrice: "15,634.79",
    total: "15,634.79",
    lienHolder: "qwerty",
    taxInclude: "no",
    salesTaxMonthly: "0",
    person1: true,
    person2: false,
    startDay: "45",
  },
  case23: {
    case: "BHPH sale with deffered sale tax as Yes ",
    caseNo: "case23",
    first_name: faker.name.firstName().replace("'", ""),
    last_name: faker.name.lastName().replace("'", ""),
    phone: faker.phone.number("3##-###-####"),
    street: faker.address.street(),
    zipcode: "75901",
    full_name: "xyz",
    bhphOrOutsideFinance: false,
    sale_date: "12/12/2022",
    vehicle_price: "10,000.00",
    totalSalePrice: "15,020.91",
    finalizeSale: true,
    saleType: "BHPH",
    typeOfSale: 2,
    apr: "22.72",
    financeCharge: "4,152.90",
    amountFinanced: "10,868.01",
    totalOfPayments: "15,020.91",
    noOfPayments: "35",
    installmentAmount: "423.66",
    dealerTradeInOffer: "7,000.00",
    payOffLoanBalance: "2,000.00",
    cashPaidToBuyer: "2,000.00",
    actualCashValue: "8,000.00",
    tradeInContains: false,
    tradeInVehicleYear: "2000",
    tradeInVehicleVIN: "5TFUM5F12AX012971",
    tradeInStock: "",
    tradeVehicleMileage: "",
    tradeInVehiclelicensePlate: " N/A ",
    tradeInVehicleMake: " ",
    tradeInVehicleModel: " ",
    differedDate: moment().add(10, "days").format("MM/DD/YYYY"),
    differedDownPaymentAmount: "0.00",
    dccGapType: "DCC",
    vendorName: "qwerty",
    dccGapDealerPrice: "200",
    dccGapCostPrice: "230",
    salesPerson: "clearent",
    salesPerson2: "aswe",
    deffDownpaymentContains: false,
    downPayment: "0",
    containsDownPayment: false,
    otherThanBHPH: false,
    commissionCalculation: "0",
    commissionRate: "1.50%",
    commission: "$ 150.00",
    profitOnVehicle: " ",
    otherCalculation: " ",
    otherCommissionRate: " ",
    otherCommission: "$ 150",
    BHPH: true,
    documentaryFee: "52.00",
    salesTax: "625.00",
    governmentFee: "162.01",
    serviceContract: "0.00",
    dccGap: "0.00",
    inventoryTax: "29.00",
    totalSalesPrice: "10,868.01",
    total: "15,020.91",
    lienHolder: "qwerty",
    taxInclude: "yes",
    salesTaxMonthly: "17.37",
    person1: true,
    person2: false,
    salesTaxRemaining: "625.00",
    salesTaxIncludedInDownpayment: "0.00",
    netDownpaymentWithSalesTax: "0.00",
    downPaymentSubjectToTax: "0.00",
    salesTaxOnDownPayment: "0.00",
    officialFeesOther: "0.26",
    titleFee: "33.00",
    licenseRegistration: "66.50",
    inspectionFeePaidToState: "14.25",
    eTagFee: "7.50",
    inspectionStationFee: "25.50",
    netTradeIn: "0.00",
    totalGovernmentFee: "243.01",
    deputyServiceFee: "15.00",
  },
  case24: {
    case: "Receipt download in Transactions for cash sale",
    caseNo: "case24",
    first_name: faker.name.firstName().replace("'", ""),
    last_name: faker.name.lastName().replace("'", ""),
    phone: faker.phone.number("3##-###-####"),
    street: faker.address.street(),
    zipcode: "75901",
    full_name: "xyz",
    bhphOrOutsideFinance: false,
    sale_date: "12/12/2022",
    vehicle_price: "10,000.00",
    totalSalePrice: "11,098.01",
    finalizeSale: true,
    saleType: "cash",
    typeOfSale: 2,
    apr: "24.82",
    financeCharge: "3,195.98",
    amountFinanced: "7,890.51",
    totalOfPayments: "11,086.49",
    noOfPayments: "35",
    installmentAmount: "312.97",
    dealerTradeInOffer: "7,000.00",
    payOffLoanBalance: "2,000.00",
    cashPaidToBuyer: "2,000.00",
    actualCashValue: "8,000.00",
    tradeInContains: false,
    tradeInVehicleYear: "2000",
    tradeInVehicleVIN: "5TFUM5F12AX012971",
    tradeInStock: "",
    tradeVehicleMileage: "",
    tradeInVehiclelicensePlate: " N/A ",
    tradeInVehicleMake: " ",
    tradeInVehicleModel: " ",
    differedDate: moment().add(10, "days").format("MM/DD/YYYY"),
    differedDownPaymentAmount: "20",
    dccGapType: "DCC",
    vendorName: "qwerty",
    dccGapDealerPrice: "200",
    dccGapCostPrice: "230",
    salesPerson: "clearent",
    salesPerson2: "clearent",
    deffDownpaymentContains: false,
    downPayment: "11,098.01",
    containsDownPayment: false,
    otherThanBHPH: true,
    commissionCalculation: "0",
    commissionRate: "2.00%",
    commission: "$ 150.00",
    profitOnVehicle: "9,687.00",
    otherCalculation: "9,769.00",
    otherCommissionRate: "2.00",
    otherCommission: "$ 195.38",
    BHPH: true,
    documentaryFee: "52.00",
    salesTax: "625.00",
    governmentFee: "162.01",
    serviceContract: "0",
    dccGap: "230.00",
    inventoryTax: "29.00",
    totalSalesPrice: "11,098.01",
    total: "11,098.01",
    lienHolder: "qwerty",
    taxInclude: "no",
    remainingAmountToPay: "0.00",
    paymentMethod: "CASH",
    checkSalesPrice: true,
  },
  case25: {
    case: "Creating a BHPH by adding down payment and receipt download",
    caseNo: "case25",
    first_name: faker.name.firstName().replace("'", ""),
    last_name: faker.name.lastName().replace("'", ""),
    phone: faker.phone.number("3##-###-####"),
    street: faker.address.street(),
    zipcode: "75901",
    full_name: "xyz",
    bhphOrOutsideFinance: true,
    sale_date: "12/12/2022",
    vehicle_price: "10,000.00",
    totalSalePrice: "15,193.43",
    finalizeSale: true,
    saleType: "BHPH",
    typeOfSale: 2,
    apr: "24.82",
    financeCharge: "4,325.42",
    amountFinanced: "10,668.01",
    totalOfPayments: "14,993.43",
    noOfPayments: "35",
    installmentAmount: "423.14",
    dealerTradeInOffer: "7,000.00",
    payOffLoanBalance: "2,000.00",
    cashPaidToBuyer: "2,000.00",
    actualCashValue: "8,000.00",
    tradeInContains: false,
    tradeInVehicleYear: "2000",
    tradeInVehicleVIN: "5TFUM5F12AX012971",
    tradeInStock: "",
    tradeVehicleMileage: "",
    tradeInVehiclelicensePlate: " N/A ",
    tradeInVehicleMake: " ",
    tradeInVehicleModel: " ",
    differedDate: moment().add(10, "days").format("MM/DD/YYYY"),
    differedDownPaymentAmount: "0.00",
    dccGapType: "DCC",
    vendorName: "qwerty",
    dccGapDealerPrice: "200",
    dccGapCostPrice: "230",
    salesPerson: "clearent",
    salesPerson2: "clearent",
    deffDownpaymentContains: false,
    downPayment: "200.00",
    containsDownPayment: true,
    otherThanBHPH: true,
    commissionCalculation: "0",
    commissionRate: "2.00%",
    commission: "$ 150.00",
    profitOnVehicle: "9,687.00",
    otherCalculation: "9,769.00",
    otherCommissionRate: "2.00",
    otherCommission: "$ 195.38",
    BHPH: true,
    documentaryFee: "52.00",
    salesTax: "625.00",
    governmentFee: "162.01",
    serviceContract: "0.00",
    dccGap: "0.00",
    inventoryTax: "29.00",
    totalSalesPrice: "10,868.01",
    total: "15,193.43",
    lienHolder: "qwerty",
    taxInclude: "no",
    paymentMethod: "CASH",
    remainingAmountToPay: "0.00",
    checkSalesPrice: false,
  },
  case26: {
    case: "Completing a Law 553 sale & validating download document  in report  ",
    caseNo: "case26",
    first_name: faker.name.firstName().replace("'", ""),
    last_name: faker.name.lastName().replace("'", ""),
    phone: faker.phone.number("3##-###-####"),
    street: faker.address.street(),
    zipcode: "75901",
    full_name: "xyz",
    bhphOrOutsideFinance: false,
    sale_date: "12/12/2022",
    vehicle_price: "10,000.00",
    totalSalePrice: "15,351.82",
    finalizeSale: true,
    saleType: "OutsideFinance",
    typeOfSale: 1,
    apr: "24.82",
    financeCharge: "4,483.81",
    amountFinanced: "10,868.01",
    totalOfPayments: "15,351.82",
    noOfPayments: "35",
    installmentAmount: "426.45",
    dealerTradeInOffer: "0.00",
    payOffLoanBalance: "0.00",
    cashPaidToBuyer: "2,000.00",
    actualCashValue: "0.00",
    tradeInContains: false,
    tradeInVehicleYear: "2000",
    tradeInVehicleVIN: "5TFUM5F12AX012971",
    tradeInStock: "",
    tradeVehicleMileage: "",
    tradeInVehiclelicensePlate: " N/A ",
    tradeInVehicleMake: " ",
    tradeInVehicleModel: " ",
    differedDate: moment().add(10, "days").format("MM/DD/YYYY"),
    differedDownPaymentAmount: "0.00",
    dccGapType: "DCC",
    vendorName: "qwerty",
    dccGapDealerPrice: "0.00",
    dccGapCostPrice: "0.00",
    salesPerson: "clearent",
    salesPerson2: "aswe",
    deffDownpaymentContains: false,
    downPayment: "0",
    containsDownPayment: false,
    otherThanBHPH: false,
    commissionCalculation: "0",
    commissionRate: "1.50%",
    commission: "$ 150.00",
    profitOnVehicle: " ",
    otherCalculation: " ",
    otherCommissionRate: " ",
    otherCommission: "$ 150",
    BHPH: true,
    documentaryFee: "52.00",
    salesTax: "625.00",
    governmentFee: "162.01",
    serviceContract: "0.00",
    dccGap: "0.00",
    inventoryTax: "29.00",
    totalSalesPrice: "10,868.01",
    total: "15,274.35",
    taxInclude: "no",
    salesTaxMonthly: "0",
    netSellingPrice: "10,000.00",
    totalDownPayment: "0.00",
    totalOfTaxAndFee: "868.01",
    dccGapProfit: "0.00",
    documentType: "Law 553",
    lienHolder: "Testone",
    oneLien: true,
    documentsUse: "reynolds-api", //"reynolds-api" |"carleton-api"|"dms-api"
  },
  case27: {
    case: "Completing a Carlton sale & validating download document  in report  ",
    caseNo: "case27",
    first_name: faker.name.firstName().replace("'", ""),
    last_name: faker.name.lastName().replace("'", ""),
    phone: faker.phone.number("3##-###-####"),
    street: faker.address.street(),
    zipcode: "75901",
    full_name: "xyz",
    bhphOrOutsideFinance: false,
    sale_date: "12/12/2022",
    vehicle_price: "10,000.00",
    totalSalePrice: "15,351.82",
    finalizeSale: true,
    saleType: "OutsideFinance",
    typeOfSale: 1,
    apr: "24.82",
    financeCharge: "4,483.81",
    amountFinanced: "10,868.01",
    totalOfPayments: "15,351.82",
    noOfPayments: "35",
    installmentAmount: "426.45",
    dealerTradeInOffer: "0.00",
    payOffLoanBalance: "0.00",
    cashPaidToBuyer: "2,000.00",
    actualCashValue: "0.00",
    tradeInContains: false,
    tradeInVehicleYear: "2000",
    tradeInVehicleVIN: "5TFUM5F12AX012971",
    tradeInStock: "",
    tradeVehicleMileage: "",
    tradeInVehiclelicensePlate: " N/A ",
    tradeInVehicleMake: " ",
    tradeInVehicleModel: " ",
    differedDate: moment().add(10, "days").format("MM/DD/YYYY"),
    differedDownPaymentAmount: "0.00",
    dccGapType: "DCC",
    vendorName: "qwerty",
    dccGapDealerPrice: "0.00",
    dccGapCostPrice: "0.00",
    salesPerson: "clearent",
    salesPerson2: "aswe",
    deffDownpaymentContains: false,
    downPayment: "0",
    containsDownPayment: false,
    otherThanBHPH: false,
    commissionCalculation: "0",
    commissionRate: "1.50%",
    commission: "$ 150.00",
    profitOnVehicle: " ",
    otherCalculation: " ",
    otherCommissionRate: " ",
    otherCommission: "$ 150",
    BHPH: true,
    documentaryFee: "52.00",
    salesTax: "625.00",
    governmentFee: "162.01",
    serviceContract: "0.00",
    dccGap: "0.00",
    inventoryTax: "29.00",
    totalSalesPrice: "10,868.01",
    total: "15,274.35",
    taxInclude: "no",
    salesTaxMonthly: "0",
    netSellingPrice: "10,000.00",
    totalDownPayment: "0.00",
    totalOfTaxAndFee: "868.01",
    dccGapProfit: "0.00",
    documentType: "Bankers",
    lienHolder: "Testone",
    oneLien: true,
    documentsUse: "carleton-api", //"reynolds-api" |"carleton-api"|"dms-api"
  },
  case28: {
    case: "Creating a BHPH by adding down payment and making Refund",
    caseNo: "case28",
    first_name: faker.name.firstName().replace("'", ""),
    last_name: faker.name.lastName().replace("'", ""),
    phone: faker.phone.number("3##-###-####"),
    street: faker.address.street(),
    zipcode: "75901",
    full_name: "xyz",
    bhphOrOutsideFinance: true,
    sale_date: "12/12/2022",
    vehicle_price: "10,000.00",
    totalSalePrice: "15,193.43",
    finalizeSale: true,
    saleType: "BHPH",
    typeOfSale: 2,
    apr: "24.82",
    financeCharge: "4,325.42",
    amountFinanced: "10,668.01",
    totalOfPayments: "14,993.43",
    noOfPayments: "35",
    installmentAmount: "423.14",
    dealerTradeInOffer: "7,000.00",
    payOffLoanBalance: "2,000.00",
    cashPaidToBuyer: "2,000.00",
    actualCashValue: "8,000.00",
    tradeInContains: false,
    tradeInVehicleYear: "2000",
    tradeInVehicleVIN: "5TFUM5F12AX012971",
    tradeInStock: "",
    tradeVehicleMileage: "",
    tradeInVehiclelicensePlate: " N/A ",
    tradeInVehicleMake: " ",
    tradeInVehicleModel: " ",
    differedDate: moment().add(10, "days").format("MM/DD/YYYY"),
    differedDownPaymentAmount: "0.00",
    dccGapType: "DCC",
    vendorName: "qwerty",
    dccGapDealerPrice: "200",
    dccGapCostPrice: "230",
    salesPerson: "clearent",
    salesPerson2: "clearent",
    deffDownpaymentContains: false,
    downPayment: "200.00",
    containsDownPayment: true,
    otherThanBHPH: true,
    commissionCalculation: "0",
    commissionRate: "2.00%",
    commission: "$ 150.00",
    profitOnVehicle: "9,687.00",
    otherCalculation: "9,769.00",
    otherCommissionRate: "2.00",
    otherCommission: "$ 195.38",
    BHPH: true,
    documentaryFee: "52.00",
    salesTax: "625.00",
    governmentFee: "162.01",
    serviceContract: "0.00",
    dccGap: "0.00",
    inventoryTax: "29.00",
    totalSalesPrice: "10,868.01",
    total: "15,193.43",
    lienHolder: "qwerty",
    taxInclude: "no",
    paymentMethod: "CASH",
    remainingAmountToPay: "0.00",
    checkSalesPrice: false,
  },
  case29: {
    case: "Creating a BHPH and modify that deal",
    caseNo: "case29",
    first_name: faker.name.firstName().replace("'", ""),
    last_name: faker.name.lastName().replace("'", ""),
    phone: faker.phone.number("3##-###-####"),
    street: faker.address.street(),
    zipcode: "75901",
    full_name: "xyz",
    bhphOrOutsideFinance: true,
    sale_date: "12/12/2022",
    vehicle_price: "10,000.00",
    totalSalePrice: "15,274.35",
    finalizeSale: true,
    saleType: "BHPH",
    typeOfSale: 2,
    apr: "24.82",
    financeCharge: "4,406.34",
    amountFinanced: "10,868.01",
    totalOfPayments: "15,274.35",
    noOfPayments: "35",
    installmentAmount: "431.08",
    dealerTradeInOffer: "7,000.00",
    payOffLoanBalance: "2,000.00",
    cashPaidToBuyer: "2,000.00",
    actualCashValue: "8,000.00",
    tradeInContains: false,
    tradeInVehicleYear: "2000",
    tradeInVehicleVIN: "5TFUM5F12AX012971",
    tradeInStock: "",
    tradeVehicleMileage: "",
    tradeInVehiclelicensePlate: " N/A ",
    tradeInVehicleMake: " ",
    tradeInVehicleModel: " ",
    differedDate: moment().add(10, "days").format("MM/DD/YYYY"),
    differedDownPaymentAmount: "0.00",
    dccGapType: "DCC",
    vendorName: "qwerty",
    dccGapDealerPrice: "200",
    dccGapCostPrice: "230",
    salesPerson: "clearent",
    salesPerson2: "clearent",
    deffDownpaymentContains: false,
    downPayment: "200.00",
    containsDownPayment: true,
    otherThanBHPH: true,
    commissionCalculation: "0",
    commissionRate: "2.00%",
    commission: "$ 150.00",
    profitOnVehicle: "9,687.00",
    otherCalculation: "9,769.00",
    otherCommissionRate: "2.00",
    otherCommission: "$ 195.38",
    BHPH: true,
    documentaryFee: "52.00",
    salesTax: "625.00",
    governmentFee: "162.01",
    serviceContract: "0.00",
    dccGap: "0.00",
    inventoryTax: "29.00",
    totalSalesPrice: "10,868.01",
    total: "15,274.35",
    lienHolder: "qwerty",
    taxInclude: "no",
    paymentMethod: "CASH",
    remainingAmountToPay: "0.00",
    checkSalesPrice: false,
    //startDay: "45",
    noOfPaymentsMd: "30",
    aprMd: "20",
    installmentAmountMd: "463.30",
    totalOfPaymentsMd: "10,868.01",
    confirmModifyDeal: true,
  },
  case30: {
    case: "validating the Sales Tax and govt Fee for Wholesale type",
    caseNo: "case30",
    first_name: faker.name.firstName().replace("'", ""),
    last_name: faker.name.lastName().replace("'", ""),
    phone: faker.phone.number("3##-###-####"),
    street: faker.address.street(),
    zipcode: "75901",
    full_name: "xyz",
    bhphOrOutsideFinance: false,
    sale_date: "12/12/2022",
    vehicle_price: "10,000.00",
    totalSalePrice: "10,250.00",
    finalizeSale: true,
    saleType: "outside finance", //"cash",
    typeOfSale: 3,
    totalOfPayments: "11,086.49",
    installmentAmount: "312.97",
    dealerTradeInOffer: "7,000.00",
    payOffLoanBalance: "2,000.00",
    cashPaidToBuyer: "2,000.00",
    actualCashValue: "8,000.00",
    tradeInContains: false,
    tradeInVehicleYear: "2000",
    tradeInVehicleVIN: "5TFUM5F12AX012971",
    tradeInStock: "",
    tradeVehicleMileage: "",
    tradeInVehiclelicensePlate: " N/A ",
    tradeInVehicleMake: " ",
    tradeInVehicleModel: " ",
    differedDate: moment().add(10, "days").format("MM/DD/YYYY"),
    differedDownPaymentAmount: "20",
    dccGapType: "DCC",
    vendorName: "qwerty",
    dccGapDealerPrice: "200",
    dccGapCostPrice: "230",
    salesPerson: "clearent",
    salesPerson2: "clearent",
    deffDownpaymentContains: false,
    downPayment: "10,250.00",
    containsDownPayment: false,
    otherThanBHPH: true,
    commissionCalculation: "0",
    commissionRate: "2.00%",
    commission: "$ 150.00",
    profitOnVehicle: "9,687.00",
    otherCalculation: "9,769.00",
    otherCommissionRate: "2.00",
    otherCommission: "$ 195.38",
    BHPH: true,
    documentaryFee: "52.00",
    salesTax: "625.00",
    governmentFee: "162.01",
    serviceContract: "0",
    dccGap: "230.00",
    inventoryTax: "29.00",
    totalSalesPrice: "11,098.01",
    total: "11,098.01",
    lienHolder: "qwerty",
    taxInclude: "no",
  },
  case31: {
    case: "Sale Finance Calculation options",
    caseNo: "case31",
    first_name: faker.name.firstName().replace("'", ""),
    last_name: faker.name.lastName().replace("'", ""),
    phone: faker.phone.number("3##-###-####"),
    street: faker.address.street(),
    zipcode: "75901",
    full_name: "xyz",
    bhphOrOutsideFinance: true,
    sale_date: "12/12/2022",
    vehicle_price: "10,000.00",
    totalSalePrice: "12,864.23",
    finalizeSale: true,
    saleType: "BHPH",
    typeOfSale: 2,
    apr: "18",
    financeCharge: "1,996.22",
    amountFinanced: "10,868.01",
    totalOfPayments: "12,864.23",
    noOfPayments: "23",
    installmentAmount: "550.00",
    dealerTradeInOffer: "7,000.00",
    payOffLoanBalance: "2,000.00",
    cashPaidToBuyer: "2,000.00",
    actualCashValue: "8,000.00",
    tradeInContains: false,
    tradeInVehicleYear: "2000",
    tradeInVehicleVIN: "5TFUM5F12AX012971",
    tradeInStock: "",
    tradeVehicleMileage: "",
    tradeInVehiclelicensePlate: " N/A ",
    tradeInVehicleMake: " ",
    tradeInVehicleModel: " ",
    differedDate: moment().add(10, "days").format("MM/DD/YYYY"),
    differedDownPaymentAmount: "0.00",
    dccGapType: "DCC",
    vendorName: "qwerty",
    dccGapDealerPrice: "200",
    dccGapCostPrice: "230",
    salesPerson: "clearent",
    salesPerson2: "clearent",
    deffDownpaymentContains: false,
    downPayment: "0.00",
    containsDownPayment: true,
    otherThanBHPH: true,
    commissionCalculation: "0",
    commissionRate: "2.00%",
    commission: "$ 150.00",
    profitOnVehicle: "9,687.00",
    otherCalculation: "9,769.00",
    otherCommissionRate: "2.00",
    otherCommission: "$ 195.38",
    BHPH: true,
    documentaryFee: "52.00",
    salesTax: "625.00",
    governmentFee: "162.01",
    serviceContract: "0.00",
    dccGap: "0.00",
    inventoryTax: "29.00",
    totalSalesPrice: "10,868.01",
    total: "15,274.35",
    lienHolder: "qwerty",
    taxInclude: "no",
    paymentMethod: "CASH",
    remainingAmountToPay: "0.00",
    checkSalesPrice: false,
    ifDeferredSalesTax: false,
    select_numberOfPayments: true,
    select_APR: false,
    select_installmentAmount: false,
    editNumberOfPayments: "24",
    editTotalInstallmentAmount: "550.00",
    editApr: "18",
  },
  case32: {
    case: "Finance Calculation options with deferred sales tax as Yes",
    caseNo: "case32",
    first_name: faker.name.firstName().replace("'", ""),
    last_name: faker.name.lastName().replace("'", ""),
    phone: faker.phone.number("3##-###-####"),
    street: faker.address.street(),
    zipcode: "75901",
    full_name: "xyz",
    bhphOrOutsideFinance: true,
    sale_date: "12/12/2022",
    vehicle_price: "10,000.00",
    totalSalePrice: "13,060.55",
    finalizeSale: true,
    saleType: "BHPH",
    typeOfSale: 2,
    apr: "18.49",
    financeCharge: "2,192.54",
    amountFinanced: "10,868.01",
    totalOfPayments: "13,060.55",
    noOfPayments: "23",
    installmentAmount: "550.00",
    dealerTradeInOffer: "7,000.00",
    payOffLoanBalance: "2,000.00",
    cashPaidToBuyer: "2,000.00",
    actualCashValue: "8,000.00",
    tradeInContains: false,
    tradeInVehicleYear: "2000",
    tradeInVehicleVIN: "5TFUM5F12AX012971",
    tradeInStock: "",
    tradeVehicleMileage: "",
    tradeInVehiclelicensePlate: " N/A ",
    tradeInVehicleMake: " ",
    tradeInVehicleModel: " ",
    differedDate: moment().add(10, "days").format("MM/DD/YYYY"),
    differedDownPaymentAmount: "0.00",
    dccGapType: "DCC",
    vendorName: "qwerty",
    dccGapDealerPrice: "200",
    dccGapCostPrice: "230",
    salesPerson: "clearent",
    salesPerson2: "clearent",
    deffDownpaymentContains: false,
    downPayment: "0.00",
    containsDownPayment: true,
    otherThanBHPH: true,
    commissionCalculation: "0",
    commissionRate: "2.00%",
    commission: "$ 150.00",
    profitOnVehicle: "9,687.00",
    otherCalculation: "9,769.00",
    otherCommissionRate: "2.00",
    otherCommission: "$ 195.38",
    BHPH: true,
    documentaryFee: "52.00",
    salesTax: "625.00",
    governmentFee: "162.01",
    serviceContract: "0.00",
    dccGap: "0.00",
    inventoryTax: "29.00",
    totalSalesPrice: "10,868.01",
    total: "15,274.35",
    lienHolder: "qwerty",
    taxInclude: "yes",
    paymentMethod: "CASH",
    remainingAmountToPay: "0.00",
    checkSalesPrice: false,
    ifDeferredSalesTax: true,
    salesTaxMonthly: "17.37",
    select_numberOfPayments: false,
    select_APR: true,
    select_installmentAmount: false,
    editNumberOfPayments: "24",
    editTotalInstallmentAmount: "550.00",
    editApr: "18",
  },
  case33: {
    case: "validating the price adjustment with vehicle price ",
    caseNo: "case33",
    first_name: faker.name.firstName().replace("'", ""),
    last_name: faker.name.lastName().replace("'", ""),
    phone: faker.phone.number("3##-###-####"),
    street: faker.address.street(),
    zipcode: "75901",
    full_name: "xyz",
    bhphOrOutsideFinance: true,
    sale_date: "12/12/2022",
    vehicle_price: "10,000.00",
    totalSalePrice: "15,236.52",
    finalizeSale: true,
    saleType: "BHPH",
    typeOfSale: 2,
    apr: "24.82",
    financeCharge: "4,395.60",
    amountFinanced: "10,840.92",
    totalOfPayments: "15,236.52",
    noOfPayments: "35",
    installmentAmount: "430.00",
    dealerTradeInOffer: "7,000.00",
    payOffLoanBalance: "2,000.00",
    cashPaidToBuyer: "2,000.00",
    actualCashValue: "8,000.00",
    tradeInContains: false,
    tradeInVehicleYear: "2000",
    tradeInVehicleVIN: "5TFUM5F12AX012971",
    tradeInStock: "",
    tradeVehicleMileage: "",
    tradeInVehiclelicensePlate: " N/A ",
    tradeInVehicleMake: " ",
    tradeInVehicleModel: " ",
    differedDate: moment().add(10, "days").format("MM/DD/YYYY"),
    differedDownPaymentAmount: "0.00",
    dccGapType: "DCC",
    vendorName: "qwerty",
    dccGapDealerPrice: "200",
    dccGapCostPrice: "230",
    salesPerson: "clearent",
    salesPerson2: "clearent",
    deffDownpaymentContains: false,
    downPayment: "200.00",
    containsDownPayment: true,
    otherThanBHPH: true,
    commissionCalculation: "0",
    commissionRate: "2.00%",
    commission: "$ 150.00",
    profitOnVehicle: "9,687.00",
    otherCalculation: "9,769.00",
    otherCommissionRate: "2.00",
    otherCommission: "$ 195.38",
    BHPH: true,
    documentaryFee: "52.00",
    salesTax: "625.00",
    governmentFee: "162.01",
    serviceContract: "0.00",
    dccGap: "0.00",
    inventoryTax: "29.00",
    totalSalesPrice: "10,868.01",
    total: "15,193.43",
    lienHolder: "qwerty",
    taxInclude: "no",
    paymentMethod: "CASH",
    remainingAmountToPay: "0.00",
    checkSalesPrice: false,
    vehiclePrice: true,
    c_downPayment: false,
    tradeAllowance: false,
    changeInstallment: "430.00",
    changesVehiclePrice: "9974.57",
    change_downpayment: "27.00",
  },
  case34: {
    case: "validating the price adjustment with daownpayment",
    caseNo: "case34",
    first_name: faker.name.firstName().replace("'", ""),
    last_name: faker.name.lastName().replace("'", ""),
    phone: faker.phone.number("3##-###-####"),
    street: faker.address.street(),
    zipcode: "75901",
    full_name: "xyz",
    bhphOrOutsideFinance: true,
    sale_date: "12/12/2022",
    vehicle_price: "10,000.00",
    totalSalePrice: "15,134.17",
    finalizeSale: true,
    saleType: "BHPH",
    typeOfSale: 2,
    apr: "24.82",
    financeCharge: "4,221.79",
    amountFinanced: "10,412.38",
    totalOfPayments: "14,634.17",
    noOfPayments: "35",
    installmentAmount: "413.00",
    dealerTradeInOffer: "7,000.00",
    payOffLoanBalance: "2,000.00",
    cashPaidToBuyer: "2,000.00",
    actualCashValue: "8,000.00",
    tradeInContains: false,
    tradeInVehicleYear: "2000",
    tradeInVehicleVIN: "5TFUM5F12AX012971",
    tradeInStock: "",
    tradeVehicleMileage: "",
    tradeInVehiclelicensePlate: " N/A ",
    tradeInVehicleMake: " ",
    tradeInVehicleModel: " ",
    differedDate: moment().add(10, "days").format("MM/DD/YYYY"),
    differedDownPaymentAmount: "0.00",
    dccGapType: "DCC",
    vendorName: "qwerty",
    dccGapDealerPrice: "200",
    dccGapCostPrice: "230",
    salesPerson: "clearent",
    salesPerson2: "clearent",
    deffDownpaymentContains: false,
    downPayment: "500.00",
    containsDownPayment: true,
    otherThanBHPH: true,
    commissionCalculation: "0",
    commissionRate: "2.00%",
    commission: "$ 150.00",
    profitOnVehicle: "9,687.00",
    otherCalculation: "9,769.00",
    otherCommissionRate: "2.00",
    otherCommission: "$ 195.38",
    BHPH: true,
    documentaryFee: "52.00",
    salesTax: "625.00",
    governmentFee: "162.01",
    serviceContract: "0.00",
    dccGap: "0.00",
    inventoryTax: "29.00",
    totalSalesPrice: "10,868.01",
    total: "15,193.43",
    lienHolder: "qwerty",
    taxInclude: "no",
    paymentMethod: "CASH",
    remainingAmountToPay: "0.00",
    checkSalesPrice: false,
    vehiclePrice: false,
    c_downPayment: true,
    tradeAllowance: false,
    changeInstallment: "413.00",
    change_downpayment: "455.63",
  },
  case35: {
    case: " validating the price adjustment with Dealer tradein offer",
    caseNo: "case35",
    first_name: faker.name.firstName().replace("'", ""),
    last_name: faker.name.lastName().replace("'", ""),
    phone: faker.phone.number("3##-###-####"),
    street: faker.address.street(),
    zipcode: "75901",
    full_name: "xyz",
    bhphOrOutsideFinance: false,
    sale_date: "12/12/2022",
    vehicle_price: "10,000.00",
    totalSalePrice: "10,488.22",
    finalizeSale: true,
    saleType: "BHPH",
    typeOfSale: 2,
    apr: "24.82",
    financeCharge: "3,025.68",
    amountFinanced: "7,462.54",
    totalOfPayments: "10,488.22",
    noOfPayments: "35",
    installmentAmount: "296.00",
    dealerTradeInOffer: "7,000.00",
    payOffLoanBalance: "2,000.00",
    cashPaidToBuyer: "2,000.00",
    actualCashValue: "8,000.00",
    tradeInContains: true,
    tradeInVehicleYear: "2000",
    tradeInVehicleVIN: "5TFUM5F12AX012971",
    tradeInStock: "",
    tradeVehicleMileage: "",
    tradeInVehiclelicensePlate: " N/A ",
    tradeInVehicleMake: " ",
    tradeInVehicleModel: " ",
    differedDate: moment().add(10, "days").format("MM/DD/YYYY"),
    differedDownPaymentAmount: "0.00",
    dccGapType: "DCC",
    vendorName: "qwerty",
    dccGapDealerPrice: "200",
    dccGapCostPrice: "230",
    salesPerson: "clearent",
    salesPerson2: "aswe",
    deffDownpaymentContains: false,
    downPayment: "0",
    containsDownPayment: false,
    otherThanBHPH: false,
    commissionCalculation: "0",
    commissionRate: "1.50%",
    commission: "$ 150.00",
    profitOnVehicle: " ",
    otherCalculation: " ",
    otherCommissionRate: " ",
    otherCommission: "$ 150",
    BHPH: true,
    documentaryFee: "52.00",
    salesTax: "187.50",
    governmentFee: "162.01",
    serviceContract: "0.00",
    dccGap: "0.00",
    inventoryTax: "29.00",
    totalSalesPrice: "7,430.51",
    total: "10,443.17",
    lienHolder: "qwerty",
    taxInclude: "no",
    salesTaxMonthly: "0",
    person1: true,
    person2: false,
    vehiclePrice: false,
    c_downPayment: false,
    tradeAllowance: true,
    changeInstallment: "296.00",
    change_downpayment: "455.63",
    change_tradeInOffer: "6969.85",
  },
};

export const salesValues = {
  cash: {
    first_name: faker.name.firstName().replace("'", ""),
    last_name: faker.name.lastName().replace("'", ""),
    phone: faker.phone.number("3##-###-####"),
    street: faker.address.street(),
    zipcode: "75901",
    sec_first_name: faker.name.firstName().replace("'", ""),
    sec_last_name: faker.name.lastName().replace("'", ""),
    sec_phone: faker.phone.number("3##-###-####"),
    sec_street: faker.address.street(),
    sec_zipcode: "75901",
    full_name: "xyz",
    bhphOrOutsideFinance: false,
    sale_date: "12/12/2022",
    vehicle_price: "10,000.00",
    totalSalePrice: "7,910.51",
    finalizeSale: true,
    saleType: "cash",
    typeOfSale: 2,
    apr: "24.82",
    financeCharge: "3,195.98",
    amountFinanced: "7,890.51",
    totalOfPayments: "11,086.49",
    noOfPayments: "35",
    installmentAmount: "312.97",
    dealerTradeInOffer: "7,000.00",
    payOffLoanBalance: "2,000.00",
    cashPaidToBuyer: "2,000.00",
    actualCashValue: "8,000.00",
    tradeInContains: false,
    tradeInVehicleYear: "2000",
    tradeInVehicleVIN: "5TFUM5F12AX012971",
    tradeInStock: "",
    tradeVehicleMileage: "",
    tradeInVehiclelicensePlate: " N/A ",
    tradeInVehicleMake: " ",
    tradeInVehicleModel: " ",
    differedDate: moment().add(10, "days").format("MM/DD/YYYY"),
    differedDownPaymentAmount: "20",
    dccGapType: "DCC",
    vendorName: "qwerty",
    dccGapDealerPrice: "200",
    dccGapCostPrice: "230",
    salesPerson: "clearent",
    salesPerson2: "clearent",
    deffDownpaymentContains: false,
    downPayment: "7,910.51",
    containsDownPayment: false,
    otherThanBHPH: true,
    commissionCalculation: "0",
    commissionRate: "2.00%",
    commission: "$ 150.00",
    profitOnVehicle: "9,687.00",
    otherCalculation: "9,769.00",
    otherCommissionRate: "2.00",
    otherCommission: "$ 195.38",
    BHPH: true,
    documentaryFee: "52.00",
    salesTax: "187.50",
    governmentFee: "162.01",
    serviceContract: "250.00",
    dccGap: "230.00",
    inventoryTax: "29.00",
    totalSalesPrice: "7,910.51",
    total: "7,910.51",
    lienHolder: "qwerty",
    taxInclude: "no",
    netSellingPrice: "11,000.00",
    totalDownPayment: "3,000.00",
    totalOfTaxAndFee: "430.51",
    jointCustomer: true,
  },
  BHPH: {
    first_name: faker.name.firstName().replace("'", ""),
    last_name: faker.name.lastName().replace("'", ""),
    phone: faker.phone.number("3##-###-####"),
    street: faker.address.street(),
    zipcode: "75901",
    sec_first_name: faker.name.firstName().replace("'", ""),
    sec_last_name: faker.name.lastName().replace("'", ""),
    sec_phone: faker.phone.number("3##-###-####"),
    sec_street: faker.address.street(),
    sec_zipcode: "75901",
    full_name: "xyz",
    bhphOrOutsideFinance: false,
    sale_date: "12/12/2022",
    vehicle_price: "10,000.00",
    totalSalePrice: "11,089.79",
    finalizeSale: true,
    saleType: "BHPH",
    typeOfSale: 2,
    apr: "24.82",
    financeCharge: "3,199.28",
    amountFinanced: "7,890.51",
    totalOfPayments: "11,089.79",
    noOfPayments: "35",
    installmentAmount: "312.97",
    dealerTradeInOffer: "7,000.00",
    payOffLoanBalance: "2,000.00",
    cashPaidToBuyer: "2,000.00",
    actualCashValue: "8,000.00",
    tradeInContains: false,
    tradeInVehicleYear: "2000",
    tradeInVehicleVIN: "5TFUM5F12AX012971",
    tradeInStock: "",
    tradeVehicleMileage: "",
    tradeInVehiclelicensePlate: " N/A ",
    tradeInVehicleMake: " ",
    tradeInVehicleModel: " ",
    differedDate: moment().add(10, "days").format("MM/DD/YYYY"),
    differedDownPaymentAmount: "20",
    dccGapType: "DCC",
    vendorName: "qwerty",
    dccGapDealerPrice: "200",
    dccGapCostPrice: "230",
    salesPerson: "clearent",
    salesPerson2: "clearent",
    deffDownpaymentContains: false,
    downPayment: "0",
    containsDownPayment: false,
    otherThanBHPH: false,
    commissionCalculation: "0",
    commissionRate: "1.50%",
    commission: "$ 150.00",
    profitOnVehicle: " ",
    otherCalculation: " ",
    otherCommissionRate: " ",
    otherCommission: " ",
    BHPH: true,
    documentaryFee: "52.00",
    salesTax: "187.50",
    governmentFee: "162.01",
    serviceContract: "250.00",
    dccGap: "230.00",
    inventoryTax: "29.00",
    totalSalesPrice: "7,910.51",
    total: "11,109.79",
    lienHolder: "qwerty",
    taxInclude: "no",
    salesTaxMonthly: "0",
    jointCustomer: false,
  },
  OutsideFinance: {
    first_name: faker.name.firstName().replace("'", ""),
    last_name: faker.name.lastName().replace("'", ""),
    phone: faker.phone.number("3##-###-####"),
    street: faker.address.street(),
    zipcode: "75901",
    sec_first_name: faker.name.firstName().replace("'", ""),
    sec_last_name: faker.name.lastName().replace("'", ""),
    sec_phone: faker.phone.number("3##-###-####"),
    sec_street: faker.address.street(),
    sec_zipcode: "75901",
    full_name: "xyz",
    bhphOrOutsideFinance: false,
    sale_date: "12/12/2022",
    vehicle_price: "10,000.00",
    totalSalePrice: "11,089.79",
    finalizeSale: true,
    saleType: "OutsideFinance",
    typeOfSale: 1,
    apr: "24.82",
    financeCharge: "3,199.28",
    amountFinanced: "7,890.51",
    totalOfPayments: "11,089.79",
    noOfPayments: "35",
    installmentAmount: "312.97",
    dealerTradeInOffer: "7,000.00",
    payOffLoanBalance: "2,000.00",
    cashPaidToBuyer: "2,000.00",
    actualCashValue: "8,000.00",
    tradeInContains: false,
    tradeInVehicleYear: "2000",
    tradeInVehicleVIN: "5TFUM5F12AX012971",
    tradeInStock: "",
    tradeVehicleMileage: "",
    tradeInVehiclelicensePlate: " N/A ",
    tradeInVehicleMake: " ",
    tradeInVehicleModel: " ",
    differedDate: moment().add(10, "days").format("MM/DD/YYYY"),
    differedDownPaymentAmount: "20",
    dccGapType: "DCC",
    vendorName: "qwerty",
    dccGapDealerPrice: "200",
    dccGapCostPrice: "230",
    salesPerson: "clearent",
    salesPerson2: "clearent",
    deffDownpaymentContains: false,
    downPayment: "0",
    containsDownPayment: false,
    otherThanBHPH: false,
    commissionCalculation: "0",
    commissionRate: "1.50%",
    commission: "$ 150.00",
    profitOnVehicle: "2,856.00",
    otherCalculation: "$3,063.00",
    otherCommissionRate: "2.00",
    otherCommission: "$ 150.00",
    BHPH: true,
    documentaryFee: "52.00",
    salesTax: "187.50",
    governmentFee: "162.01",
    serviceContract: "250.00",
    dccGap: "230.00",
    inventoryTax: "29.00",
    totalSalesPrice: "7,910.51",
    total: "11,109.79",
    lienHolder: "qwerty",
    taxInclude: "no",
    jointCustomer: true,
    oneLien: true,
    secLien: false,
  },
  Wholesale: {
    first_name: faker.name.firstName().replace("'", ""),
    last_name: faker.name.lastName().replace("'", ""),
    phone: faker.phone.number("3##-###-####"),
    street: faker.address.street(),
    zipcode: "75901",
    sec_first_name: faker.name.firstName().replace("'", ""),
    sec_last_name: faker.name.lastName().replace("'", ""),
    sec_phone: faker.phone.number("3##-###-####"),
    sec_street: faker.address.street(),
    sec_zipcode: "75901",
    full_name: "xyz",
    bhphOrOutsideFinance: false,
    sale_date: "12/12/2022",
    vehicle_price: "10,000.00",
    totalSalePrice: "7,480.00",
    finalizeSale: true,
    saleType: "Wholesale",
    typeOfSale: 3,
    apr: "24.82",
    financeCharge: "3,195.98",
    amountFinanced: "7,890.51",
    totalOfPayments: "11,086.49",
    noOfPayments: "35",
    installmentAmount: "312.97",
    dealerTradeInOffer: "7,000.00",
    payOffLoanBalance: "2,000.00",
    cashPaidToBuyer: "2,000.00",
    actualCashValue: "8,000.00",
    tradeInContains: false,
    tradeInVehicleYear: "2000",
    tradeInVehicleVIN: "5TFUM5F12AX012971",
    tradeInStock: "",
    tradeVehicleMileage: "",
    tradeInVehiclelicensePlate: " N/A ",
    tradeInVehicleMake: " ",
    tradeInVehicleModel: " ",
    differedDate: moment().add(10, "days").format("MM/DD/YYYY"),
    differedDownPaymentAmount: "20",
    dccGapType: "DCC",
    vendorName: "qwerty",
    dccGapDealerPrice: "200",
    dccGapCostPrice: "230",
    salesPerson: "clearent",
    salesPerson2: "clearent",
    deffDownpaymentContains: false,
    downPayment: "0",
    containsDownPayment: false,
    otherThanBHPH: false,
    commissionCalculation: "7,682.00",
    commissionRate: "2.00%",
    commission: "$ 150.00",
    profitOnVehicle: "9,687.00",
    otherCalculation: "9,842.00",
    otherCommissionRate: "2.00%",
    otherCommission: "$ 196.84",
    BHPH: true,
    documentaryFee: "0.00",
    salesTax: "0.00",
    governmentFee: "0.00",
    serviceContract: "250.00",
    dccGap: "230.00",
    inventoryTax: "0.00",
    totalSalesPrice: "7,480.00",
    total: "7,480.00",
    lienHolder: "qwerty",
    taxInclude: "no",
    jointCustomer: true,
  },
};
export const inventoryValues = {
  vehicleDetails: {
    vin: vinGenerator.generateVin(),
    mileage: faker.random.numeric(5),
    vehiclePrice: faker.random.numeric(4),
    buyerFee: faker.random.numeric(2),
  },
};
